#!/bin/bash
# Slack Channels Configuration
# Auto-generated: 2026-02-12

# Channel IDs
export CHANNEL_SPRINT_CURRENT="C0AD8798FL7"
export CHANNEL_ANNOUNCEMENTS="C0ADH906PFD"
export CHANNEL_JIRA_UPDATES="C0AE2J6S3KK"
export CHANNEL_JIRA_BLOCKERS="C0ADPLD3A10"
export CHANNEL_MISSION_CONTROL="C0AE2J7HW9F"
export CHANNEL_AGENT_LOGS="C0ADH90LDB5"
export CHANNEL_AGENT_ALERTS="C0ADPLDC2DQ"
export CHANNEL_CREW_DEV="C0AEHUXU4D6"
export CHANNEL_CREW_QA="C0ADH8ZTDM1"
export CHANNEL_CREW_PRODUCT="C0ADL7XA1DK"
export CHANNEL_REVENUEOS_API="C0ADL7XDHBP"
export CHANNEL_REVENUEOS_FRONTEND="C0ADMJPKPGW"
export CHANNEL_REVENUEOS_INFRA="C0ADT8VMHM2"
export CHANNEL_REVENUEOS_GENERAL="C0ADT8VUSUU"
export CHANNEL_STANDUP="C0AD879LG4X"
export CHANNEL_SOCIAL="C0ADPKM29CJ"
export CHANNEL_EMPRESA="C0ADL7564BF"
